# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

data_test <- matrix("test",nrow = 3,ncol = 5)
as.data.frame(data_test)
test_that("prepare_input works properly and show error if needed", {
  expect_error(prepare_input(data_test))
})
