# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' assess_gower
#'
#' @param data a dataframe
#' @param col_select a vector
#' @param id a number
#' @param date a number
#' @param m a boolean
#' @param a a boolean
#' @param weights a vector
#' @param graph a boolean
#'
#' @return a list containing the components clean_data, gower_dist, aggl.clust.c
#' @export
#'
#' @examples
#' # Example with your dataset in "inst/"
#' datafile <- system.file("data_test.csv", package = "strainselect")
#' raw_data <- read.csv(datafile, sep = ";",header = T)
#' # Apply my function
#' assess_gower(raw_data,col_select = c(7,10,13,14,17,24), 
#'                       id=1,date=17,m=FALSE,a=TRUE, graph = T)
assess_gower <- function(data, col_select=c(1:length(data)), id =1, date=0,
                         m=FALSE, a=TRUE, weights = rep.int(1, p), graph = TRUE){
  clean_data <- prepare_input(data,col_select=col_select, id =id, date=date,
                              m=m, a=a)
  p=length(clean_data)
  gower_dist <- daisy(clean_data, metric = "gower", weights = weights)
  aggl.clust.c <- hclust(gower_dist, method = "complete")
  if (graph) {
    plot(aggl.clust.c,main = "Agglomerative, complete linkages")
  }
  return(list(clean_data=clean_data,gower_dist=gower_dist, aggl.clust.c=aggl.clust.c))
}
