# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' cstats_table
#'
#' @param dist a distance object 
#' @param tree a dendrogram object
#' @param k a number
#' @param l a number
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' # Example with your dataset in "inst/"
#' datafile <- system.file("data_test.csv", package = "strainselect")
#' raw_data <- read.csv(datafile, sep = ";",header = T)
#' gower <- assess_gower(raw_data)
#' # Apply my function
#' cstats_table(dist = gower$gower_dist, tree = gower$aggl.clust.c, k = 50,l = 10)
 cstats_table <- function(dist, tree, k,l) {
   n = k/l
   clust.assess <- c("cluster.number","n","within.cluster.ss","average.within","average.between",
                     "wb.ratio","dunn2","avg.silwidth")
   clust.size <- c("cluster.size")
   stats.names <- c()
   row.clust <- c()
   output.stats <- matrix(ncol = n, nrow = length(clust.assess))
   cluster.sizes <- matrix(ncol = n, nrow = n)
   for(i in 1:n){
       row.clust[i] <- paste("Cluster-", i*l, " size")
   }
    for(i in 1:n){
     print(i*l)
     stats.names[i] <- paste("Test", i*l-1)
     
     for(j in seq_along(clust.assess)){
       output.stats[j, i] <- unlist(cluster.stats(d = dist, clustering = cutree(tree, k = i*l))[clust.assess])[j]
       
     }
     
     for(d in 1:n) {
       cluster.sizes[d, i] <- unlist(cluster.stats(d = dist, clustering = cutree(tree, k = i*l))[clust.size])[d*l]
       dim(cluster.sizes[d, i]) <- c(length(cluster.sizes[i]), 1)
       cluster.sizes[d, i]
       
     }
   }
   output.stats.df <- data.frame(output.stats)
   cluster.sizes <- data.frame(cluster.sizes)
   cluster.sizes[is.na(cluster.sizes)] <- 0
   rows.all <- c(clust.assess, row.clust)
   # rownames(output.stats.df) <- clust.assess
   output <- rbind(output.stats.df, cluster.sizes)
   colnames(output) <- stats.names[1:n]
   rownames(output) <- rows.all
   is.num <- sapply(output, is.numeric)
   output[is.num] <- lapply(output[is.num], round, 2)
   output
 }
