# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' prepare_upset
#'
#' @param prepared_data a dataframe
#'
#' @return a dataframe
#' @export
#'
#' @examples
#' # Example with your dataset in "inst/"
#' datafile <- system.file("data_test.csv", package = "strainselect")
#' raw_data <- read.csv(datafile, sep = ";",header = T)
#' prepared_data <- prepare_input(raw_data,col_select = c(7,10,13,14,17,24),
#'               id=1,date=17,m=FALSE,a=TRUE)
#' # Apply my function
#' prepare_upset(prepared_data)
prepare_upset<- function(prepared_data){
 upset_data <- data.frame(row.names = rownames(prepared_data))
 metadata <- colnames(prepared_data)
 for (i in 1:ncol(prepared_data)){
   vect <- unique(prepared_data[,i])
   tab <- matrix(0,nrow(prepared_data),length(vect))
   col.names <- NULL
   for (j in 1:length(vect)){
     col.names <- c(col.names,paste(metadata[i],"_",vect[j]))
     for (k in 1:nrow(prepared_data)){
       if (is.na(prepared_data[k,i])==F){
         if(prepared_data[k,i]==vect[j]){
           tab[k,j] <- 1
         }
       }
     }
   }
   colnames(tab) <- col.names
   upset_data <- cbind(upset_data,tab)
 } 
 upset_data
}

