# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' prepare_input
#'
#' @param data a dataframe
#' @param col_select a vector
#' @param id a number
#' @param date a number
#' @param m a boolean
#' @param a a boolean
#'
#' @return a dataframe
#' @export
#' @examples
#' 
#' # Example with your dataset in "inst/"
#' datafile <- system.file("data_test.csv", package = "strainselect")
#' raw_data <- read.csv(datafile, sep = ";",header = T)
#' # Apply my function
#' prepare_input(raw_data,col_select = c(7,10,13,14,17,24),
#'               id=1,date=17,m=FALSE,a=TRUE)
prepare_input <- function (data, col_select=c(1:length(data)), id =1, date=0,
                           m=FALSE, a=TRUE) {
  duplicate <- which(duplicated(data[,id]))
  if (length(duplicate)!=0) {
    stop ( "duplicate ID : " , paste(data[duplicate,id], collapse = ", "))
  } else {
    print("no duplicate ID")
  }
  rownames(data) <- data[,id]
  col_select<-col_select[! col_select %in% date]
  clean_data <- data[,col_select]
  if (date!=0){
    if(a){
      clean_data$ANNEE <- substr(data[,date],7,10)
    }
    if(m){
      clean_data$MOIS <- substr(data[,date],4,5)
    }
  }
  clean_data[is.na(clean_data)] <- "unknown"
  clean_data[] <- lapply(clean_data, factor)
  print(colnames(clean_data))
  str(clean_data)
  clean_data
}
