# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' select_profiles
#'
#' @param profiles a data frame
#' @param prepared_data a data frame
#'
#' @return a data frame
#' @export
#'
#' @examples
#' # Example with your dataset in "inst/"
#' datafile <- system.file("data_test.csv", package = "strainselect")
#' raw_data <- read.csv(datafile, sep = ";",header = T)
#' prepared_data <- prepare_input(raw_data,col_select = c(7,10,13,14,17,24),
#'               id=1,date=17,m=FALSE,a=TRUE)
#' upset_data <- prepare_upset(prepared_data)
#' upset_profiles <- define_profiles(upset_data)
#' # Apply my function
#' select_profiles(upset_profiles,prepared_data)
select_profiles <- function(profiles, prepared_data){
  selected_data <- prepared_data
  selected_data$group <- profiles$group
  selected_data$size <- profiles$freq
  k<- max(profiles$group)
  n=nrow(selected_data)
  selection <-rep(NA,k)
  for (j in 1:k){
      selection[j] <-sample(profiles$names[profiles$group==j],1)
  }
  for (i in 1:n){
    for (j in 1:k){
      if (selected_data$group[i]==j){
        selected_data$selected[i] <- selection[j]
      }
    }
  }
  selected_data
}
