# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' select_silhouette
#'
#' @param prepared_data a data frame
#' @param dist a distance object
#' @param k a integer
#' @param isdiss logical value specifying wether x is a dissimilarity matrix
#' @param hc_func the hierarchical clustering function to be used
#' @param hc_method he agglomeration method to be used
#'
#' @return a data frame
#' @export
#'
#' @examples
#' datafile <- system.file("data_test.csv", package = "strainselect")
#' raw_data <- read.csv(datafile, sep = ";",header = T)
#' gower <- assess_gower(prepared_data, graph = T)
#' prepared_data <- prepare_input(raw_data,col_select = c(7,10,13,14,17,24),
#'               id=1,date=17,m=FALSE,a=TRUE)
#' 
#'  select_silhouette(dist=gower$gower_dist,prepared_data = prepared_data, k=50, isdiss = inherits(gower$gower_dist, "dist"),hc_func = "hclust", hc_method = "complete")
 select_silhouette <- function (prepared_data, dist, k, isdiss = inherits(gower$gower_dist, "dist"),
                               hc_func = "hclust", hc_method = "complete") {
   clust2 <- hcut(dist, k, isdiss,hc_func, hc_method)
   silh <- fviz_silhouette(clust2)
   selected_data <- prepared_data
   selected_data$cluster <- clust2$cluster
   n=nrow(selected_data)
   selection <- rep(NA,k)
   for(i in 1:k){
     max_silh_i <- silh$data[which(silh$data$sil_width==max(silh$data$sil_width[silh$data$cluster==i])&silh$data$cluster==i),]
     if (nrow(max_silh_i)==1){
       selection[i] <- as.character(max_silh_i$name)
     } else {
       selection[i] <- as.character(sample(max_silh_i$name,1))
     } 
   }
   for (i in 1:n){
     for (j in 1:k){
       if (selected_data$cluster[i]==j){
         selected_data$size[i] <- clust2$size[j]
         selected_data$selected[i] <- selection[j]
         
       }
     }
   }
   selected_data
 }
